# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: postgresql
    binary: postgresql
    buildmode: "c-shared"
    flags:
      - -tags=zig
    ldflags:
    - -s -w -X github.com/litesql/postgresql/extension.version={{.Version}} -X github.com/litesql/postgresql/extension.commit={{.Commit}} -X github.com/litesql/postgresql/extension.date={{.Date}}
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target x86_64-linux-gnu

  - id: postgresql_linux_arm64
    binary: postgresql
    buildmode: "c-shared"
    flags:
      - -tags=zig
    ldflags:
    - -s -w -X github.com/litesql/postgresql/extension.version={{.Version}} -X github.com/litesql/postgresql/extension.commit={{.Commit}} -X github.com/litesql/postgresql/extension.date={{.Date}}
    goos:
      - linux
    goarch:
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target aarch64-linux-gnu

  - id: postgresql_windows
    binary: postgresql
    buildmode: "c-shared"
    flags:
      - -tags=zig
    ldflags:
    - -s -w -X github.com/litesql/postgresql/extension.version={{.Version}} -X github.com/litesql/postgresql/extension.commit={{.Commit}} -X github.com/litesql/postgresql/extension.date={{.Date}}
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=zig cc -target x86_64-windows

  - id: postgresql_darwin
    binary: postgresql
    buildmode: "c-shared"
    ldflags:
    - -s -w -X github.com/litesql/postgresql/extension.version={{.Version}} -X github.com/litesql/postgresql/extension.commit={{.Commit}} -X github.com/litesql/postgresql/extension.date={{.Date}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=1
      - CC=o64-clang

  - id: pg2sqlite
    binary: pg2sqlite
    main: ./cmd/pg2sqlite
    ldflags: -s -w
    env:
      - CGO_ENABLED=0
    goarch:
      - amd64
      - arm64

archives:
  - id: postgresql
    formats: [tar.gz]
    ids: [postgresql, postgresql_linux_arm64, postgresql_windows, postgresql_darwin]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      postgresql_v
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - none*

  - id: pg2sqlite
    formats: [tar.gz]
    ids: [pg2sqlite]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      pg2sqlite_v
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - none*
changelog:
  disable: true

release:  
  github:
    owner: litesql
    name: postgresql

  draft: false